POST http://localhost:8080/api/auth/finalise-reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQGdtYWlsLmNvbSIsImlhdCI6MTczOTU1MzkyNiwiZXhwIjoxNzM5NTU1NzI2fQ.MyvRNB7pOcJxurUyGBXPekjHe8FtQQAzkiqTDZExpmA",
  "password": "newPassword",
  "confirmPassword": "newPassword"
}